apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aqua
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: aqua
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.startingCSV }}
