apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: og-nondefaultnamespace
  namespace: openshift-gitops
  labels:
    repo: local
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nondefaultnamespace
  project: default
  source:
    helm:
      releaseName: operatorname
    path: operator-group
    repoURL: git@github.com:digital-iq/ocp-operator-helmcharts.git
    targetRevision: ocp-4.11
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
